# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"
    webp:
        generate: true
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        logo_thumb:
            quality: 75
            filters:
                thumbnail: { size: [350, 350], mode: outbound }