# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        logo_thumb:
            quality: 75
            filters:
                thumbnail: { size: [350, 350], mode: outbound }
        
        avatar_720:
            quality: 75
            filters:
                thumbnail: { size: [720, 720], mode: outbound }
        
        logo_720:
            quality: 75
            filters:
                thumbnail: { size: [720, 720], mode: outbound }
                
        avatar_256:
            quality: 75
            filters:
                thumbnail: { size: [256, 256], mode: outbound }

        logo_256:
            quality: 75
            filters:
                thumbnail: { size: [256, 256], mode: outbound }

        avatar_40:
            quality: 75
            filters:
                thumbnail: { size: [40, 40], mode: outbound }

        logo_40:
            quality: 75
            filters:
                thumbnail: { size: [40, 40], mode: outbound }