vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        team_logo:
            uri_prefix: /images/teams
            upload_destination: '%kernel.project_dir%/public/images/teams'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true